ALL_ATTRIBUTES = ['AGE_RANGE', 'BEARD', 'EMOTIONS', 'EYE_DIRECTION',
                        'EYEGLASSES', 'EYES_OPEN', 'GENDER', 'MOUTH_OPEN', 
                        'MUSTACHE', 'FACE_OCCLUDED', 'SMILE', 'SUNGLASSES']

n = []

print(ALL_ATTRIBUTES) 